
###
POST http://localhost:5000/newComment

{
           "id":20,
          "content": "TEST",
          "createdAt": "TEST",
          "score": 0,
          "user": {
            "image": {
              "png": "TEST",
              "webp": "TEST",
            },
            "username": user.username,
          },
          "replies": []
}